# 系統保留字用大寫,養成習慣

CREATE DATABASE db01;
CREATE SCHEMA db02;
CREATE DATABASE IF NOT EXISTS db01;
CREATE SCHEMA `db03` ;

USE db01;
SHOW DATABASES;
SHOW CHAR SET;
SHOW COLLATION;
SHOW COLLATION LIKE 'big5%';

DROP DATABASE db03;

ALTER DATABASE DB02
CHARACTER SET 'BIG5'
COLLATE 'BIG5_CHINESE_CI'; 

SELECT @@character_set_database,@@collation_database;